
# QPLIB B&B Dataset Generation

This notebook is **only for QPLIB**.

It starts from the final 143 fully bounded QPLIB pickles and generates the raw B&B dataset needed before the later learned time-budget / relaxation-selection stages.

Pipeline:

1. Load and validate the final QPLIB bounded pickles.
2. Find a verified feasible incumbent for each instance:
   - multi-start Ipopt,
   - manual feasibility check,
   - Gurobi feasibility-repair fallback if needed.
3. Run two separate fixed-budget B&B trees:
   - LP tree,
   - SDP′ tree.
4. Preserve the existing thesis B&B rules:
   - BFS,
   - sequential branching,
   - midpoint split,
   - common incumbent for LP and SDP′.
5. Save:
   - feasible incumbent CSV/pickle,
   - node-level LIVE CSV/parquet,
   - per-instance B&B summary.

This notebook does **not** run MINLPLib.

In [3]:

# ============================================================
# 0. CONFIG + IMPORTS
# ============================================================

from pathlib import Path
from dataclasses import dataclass, field
from collections import deque
from typing import Any, Dict, List, Optional, Tuple

import os
import sys
import gc
import math
import time
import pickle
import traceback
import importlib
import inspect

import numpy as np
import pandas as pd

BASE = Path(r"C:\Users\suuser\Desktop\minlplib")
QPLIB_BASE = BASE / "Areview" / "qplib"

# Final QPLIB dataset already prepared earlier.
QPLIB_INPUT_DIR = QPLIB_BASE / "pickles_nlt300_mge1_bounded"

# New outputs for the QPLIB B&B extension.
QPLIB_BB_DIR = QPLIB_BASE / "bb_qplib"
QPLIB_BB_DIR.mkdir(parents=True, exist_ok=True)

QPLIB_FEASIBLE_CSV = QPLIB_BB_DIR / "qplib_feasible_ubs.csv"
QPLIB_FEASIBLE_PKL = QPLIB_BB_DIR / "qplib_feasible_points.pkl"

QPLIB_LIVE_CSV = QPLIB_BB_DIR / "qplib_bb_fixed100_LIVE.csv"
QPLIB_LIVE_PARQUET = QPLIB_BB_DIR / "qplib_bb_fixed100_LIVE.parquet"
QPLIB_BB_SUMMARY_CSV = QPLIB_BB_DIR / "qplib_bb_fixed100_instance_summary.csv"
QPLIB_BB_SKIPPED_CSV = QPLIB_BB_DIR / "qplib_bb_fixed100_SKIPPED.csv"

# Current verified Fusion/Gurobi QCQP solver.
SOLVER_MODULE = "qcqp_solverminlplib"

# ------------------------------------------------------------
# QPLIB incumbent search
# ------------------------------------------------------------
RUN_IPOPT = True
IPOPT_TIME_LIMIT_PER_START = 20.0
IPOPT_MAX_ITER = 1000
IPOPT_TOL = 1e-7
IPOPT_CONSTR_VIOL_TOL = 1e-7

N_RANDOM_STARTS = 5
RANDOM_SEED = 123
RANDOM_RADIUS_CAP = 100.0

RUN_GUROBI_REPAIR_FALLBACK = True
GUROBI_REPAIR_TIME_LIMIT = 60.0

FEAS_TOL = 1e-6
BOUND_TOL = 1e-7

# Resume incumbent search if output already exists.
RESUME_FEASIBLE_SEARCH = True

# ------------------------------------------------------------
# QPLIB first B&B data-generation run
# ------------------------------------------------------------
FIXED_NODES_LP = 100
FIXED_NODES_SDPP = 100
MAX_DEPTH = 999
MIN_WIDTH = 1e-10
PRUNE_TOL = 1e-8

BRANCH_RULE = "sequential"
SPLIT_RULE = "midpoint"

USE_BLOCKS = True
BLOCK_TOL = 1e-8
VERBOSE_BLOCKS = False
PRUNE_MATRICES = False
MIN_BLOCK_EDGES = 0

FLUSH_EVERY_NODES = 5
RESUME_BB = True

# For quick testing, e.g. 5. Use None for all 143.
MAX_QPLIB_INSTANCES = None

# ------------------------------------------------------------
# Target definition used in the paper
# ------------------------------------------------------------
ETA = 1e-3
EPS = 1e-2

print("QPLIB input dir:", QPLIB_INPUT_DIR)
print("QPLIB B&B output dir:", QPLIB_BB_DIR)

QPLIB input dir: C:\Users\suuser\Desktop\minlplib\Areview\qplib\pickles_nlt300_mge1_bounded
QPLIB B&B output dir: C:\Users\suuser\Desktop\minlplib\Areview\qplib\bb_qplib

In [4]:

# ============================================================
# 1. LOAD CURRENT SOLVER + OPTIONAL INCUMBENT SOLVERS
# ============================================================

if str(BASE) not in sys.path:
    sys.path.insert(0, str(BASE))

solver_module = importlib.import_module(SOLVER_MODULE)
solver_module = importlib.reload(solver_module)
QCQPSolver = solver_module.QCQPSolver

print("Solver file:", solver_module.__file__)
print("QCQPSolver signature:", inspect.signature(QCQPSolver.__init__))

try:
    import cyipopt
    HAS_CYIPOPT = True
except Exception as e:
    cyipopt = None
    HAS_CYIPOPT = False
    print("[WARN] cyipopt unavailable:", repr(e))

try:
    import gurobipy as gp
    from gurobipy import GRB
    HAS_GUROBI = True
except Exception as e:
    gp = None
    GRB = None
    HAS_GUROBI = False
    print("[WARN] gurobipy unavailable:", repr(e))

print("HAS_CYIPOPT:", HAS_CYIPOPT)
print("HAS_GUROBI :", HAS_GUROBI)

Solver file: C:\Users\suuser\Desktop\minlplib\qcqp_solverminlplib.py
QCQPSolver signature: (self, A_list, b_list, c_list, l, u, use_blocks=True, block_tol=1e-08, verbose_blocks=True, prune_matrices=False, min_block_edges=0)
HAS_CYIPOPT: True
HAS_GUROBI : True

In [5]:

# ============================================================
# 2. QPLIB DATA HELPERS
# Canonical convention:
#     0.5 x^T A x + b^T x + c
# ============================================================

def _get(obj, key, default=None):
    if isinstance(obj, dict):
        return obj.get(key, default)
    return getattr(obj, key, default)


def _to_dict(obj):
    if isinstance(obj, dict):
        return dict(obj)
    if hasattr(obj, "__dict__"):
        return dict(obj.__dict__)
    raise TypeError(f"Unsupported pickle object type: {type(obj).__name__}")


def load_qplib_pickle(pkl_path: Path) -> Dict[str, Any]:
    with open(pkl_path, "rb") as f:
        obj = pickle.load(f)

    d = _to_dict(obj)

    A_list = [np.asarray(A, dtype=float) for A in d["A_list"]]
    b_list = [np.asarray(b, dtype=float).reshape(-1) for b in d["b_list"]]
    c_list = [float(np.asarray(c, dtype=float).reshape(-1)[0]) for c in d["c_list"]]

    # Final Stage-5 files may contain l_work/u_work as well as l/u.
    # Prefer working bounds if they exist and are finite.
    l_work = d.get("l_work", None)
    u_work = d.get("u_work", None)

    if l_work is not None and u_work is not None:
        l_try = np.asarray(l_work, dtype=float).reshape(-1)
        u_try = np.asarray(u_work, dtype=float).reshape(-1)
        if np.all(np.isfinite(l_try)) and np.all(np.isfinite(u_try)):
            l, u = l_try, u_try
        else:
            l = np.asarray(d["l"], dtype=float).reshape(-1)
            u = np.asarray(d["u"], dtype=float).reshape(-1)
    else:
        l = np.asarray(d["l"], dtype=float).reshape(-1)
        u = np.asarray(d["u"], dtype=float).reshape(-1)

    n = len(l)

    if len(A_list) != len(b_list) or len(A_list) != len(c_list):
        raise ValueError("A_list, b_list, c_list lengths disagree.")

    for k, (A, b) in enumerate(zip(A_list, b_list)):
        if A.shape != (n, n):
            raise ValueError(f"A[{k}] shape {A.shape}, expected {(n,n)}.")
        if b.shape != (n,):
            raise ValueError(f"b[{k}] shape {b.shape}, expected {(n,)}.")

    if not np.all(np.isfinite(l)) or not np.all(np.isfinite(u)):
        raise ValueError("Final QPLIB B&B instance still has non-finite bounds.")
    if np.any(l > u):
        raise ValueError("Invalid bounds: some lower bound exceeds upper bound.")

    name = str(
        d.get("name")
        or d.get("instance_name")
        or d.get("problem_name")
        or pkl_path.stem
    )

    return {
        "file": str(pkl_path),
        "name": name,
        "pkl_stem": pkl_path.stem,
        "instance_id": d.get("instance_id", d.get("id", name)),
        "probtype": d.get("probtype"),
        "integrality_relaxed": d.get("integrality_relaxed"),
        "convex": d.get("convex", d.get("qplib_convex")),
        "n": n,
        "m_original": d.get("m_original"),
        "m_solver": len(A_list) - 1,
        "A_list": A_list,
        "b_list": b_list,
        "c_list": c_list,
        "l": l,
        "u": u,
        "raw": d,
    }


def sym_A(A):
    A = np.asarray(A, dtype=float)
    return 0.5 * (A + A.T)


def q_value(A, b, c, x):
    """
    QPLIB/current-solver canonical form:
        0.5*x^T A x + b^T x + c

    Using sym_A is value-equivalent for real x and gives the correct gradient.
    """
    x = np.asarray(x, dtype=float)
    S = sym_A(A)
    return float(0.5 * x @ S @ x + np.asarray(b, dtype=float) @ x + float(c))


def q_grad(A, b, x):
    x = np.asarray(x, dtype=float)
    return sym_A(A) @ x + np.asarray(b, dtype=float)


def objective_value(data, x):
    return q_value(data["A_list"][0], data["b_list"][0], data["c_list"][0], x)


def constraint_values(data, x):
    vals = [
        q_value(data["A_list"][k], data["b_list"][k], data["c_list"][k], x)
        for k in range(1, len(data["A_list"]))
    ]
    return np.asarray(vals, dtype=float)


def check_feasibility(data, x, feas_tol=FEAS_TOL, bound_tol=BOUND_TOL):
    x = np.asarray(x, dtype=float).reshape(-1)
    l = data["l"]
    u = data["u"]

    lower_viol = np.maximum(l - x, 0.0)
    upper_viol = np.maximum(x - u, 0.0)
    max_bound_violation = float(
        max(
            np.max(lower_viol) if lower_viol.size else 0.0,
            np.max(upper_viol) if upper_viol.size else 0.0,
        )
    )

    g = constraint_values(data, x)
    max_constraint_violation = float(
        np.max(np.maximum(g, 0.0)) if g.size else 0.0
    )

    return {
        "is_feasible": bool(
            max_bound_violation <= bound_tol
            and max_constraint_violation <= feas_tol
        ),
        "max_bound_violation": max_bound_violation,
        "max_constraint_violation": max_constraint_violation,
    }


pkl_files = sorted(QPLIB_INPUT_DIR.glob("*.pkl"))
if MAX_QPLIB_INSTANCES is not None:
    pkl_files = pkl_files[:MAX_QPLIB_INSTANCES]

print("QPLIB B&B input pickles:", len(pkl_files))

validation_rows = []
for p in pkl_files:
    try:
        d = load_qplib_pickle(p)
        validation_rows.append({
            "name": d["name"],
            "file": p.name,
            "n": d["n"],
            "m_solver": d["m_solver"],
            "probtype": d["probtype"],
            "integrality_relaxed": d["integrality_relaxed"],
            "convex": d["convex"],
            "valid": True,
            "reason": "",
        })
    except Exception as e:
        validation_rows.append({
            "name": p.stem,
            "file": p.name,
            "valid": False,
            "reason": repr(e),
        })

validation_df = pd.DataFrame(validation_rows)
display(validation_df.head())
print("Valid:", int(validation_df["valid"].sum()), "/", len(validation_df))

QPLIB B&B input pickles: 143

,name,file,n,m_solver,probtype,integrality_relaxed,convex,valid,reason
0,QPLIB_0018,QPLIB_0018.pkl,50,2,QCL,True,None,True,
1,QPLIB_0031,QPLIB_0031.pkl,60,33,QML,True,None,True,
2,QPLIB_0032,QPLIB_0032.pkl,100,53,QML,True,None,True,
3,QPLIB_0067,QPLIB_0067.pkl,80,1,QBL,True,None,True,
4,QPLIB_0343,QPLIB_0343.pkl,50,2,QCL,True,None,True,

Valid: 143 / 143

In [6]:

# ============================================================
# 3. QPLIB FEASIBLE INCUMBENT SEARCH
# Same high-level strategy as the MINLPLib B&B notebook:
#   multi-start Ipopt -> manual feasibility check -> Gurobi repair fallback.
# ============================================================

def make_start_points(l, u, n_random=N_RANDOM_STARTS, seed=0):
    rng = np.random.default_rng(seed)

    l = np.asarray(l, dtype=float)
    u = np.asarray(u, dtype=float)
    width = u - l

    starts = []

    mid = 0.5 * (l + u)
    starts.append(("midpoint", mid.copy()))
    starts.append(("clipped_zero", np.clip(np.zeros_like(l), l, u)))
    starts.append(("lower_25pct", l + 0.25 * width))
    starts.append(("upper_75pct", l + 0.75 * width))

    # Same idea as MINLPLib: local random starts so giant boxes do not
    # produce absurd starting values.
    radius = np.minimum(0.25 * width, RANDOM_RADIUS_CAP)

    for r in range(n_random):
        x = mid + rng.uniform(-1.0, 1.0, size=len(l)) * radius
        x = np.clip(x, l, u)
        starts.append((f"random_{r}", x))

    unique = []
    seen = set()
    for name, x in starts:
        key = tuple(np.round(x, decimals=10))
        if key not in seen:
            seen.add(key)
            unique.append((name, x))

    return unique


class IpoptQPLIBProblem:
    def __init__(self, data):
        self.data = data
        self.n = data["n"]
        self.m = data["m_solver"]

    def objective(self, x):
        return objective_value(self.data, x)

    def gradient(self, x):
        return q_grad(
            self.data["A_list"][0],
            self.data["b_list"][0],
            x
        )

    def constraints(self, x):
        return constraint_values(self.data, x)

    def jacobian(self, x):
        rows = []
        for k in range(1, len(self.data["A_list"])):
            rows.append(
                q_grad(
                    self.data["A_list"][k],
                    self.data["b_list"][k],
                    x
                )
            )

        if not rows:
            return np.array([], dtype=float)

        return np.vstack(rows).reshape(-1)


def solve_with_ipopt_qplib(data, starts):
    if not HAS_CYIPOPT or not RUN_IPOPT:
        return {
            "best_x": None,
            "best_ub": np.inf,
            "best_start": None,
            "attempts": 0,
            "status_summary": "cyipopt_not_available_or_disabled",
            "runtime": 0.0,
        }

    n = data["n"]
    m = data["m_solver"]

    # All canonicalized QPLIB constraints are <= 0.
    cl = -1e19 * np.ones(m, dtype=float)
    cu = np.zeros(m, dtype=float)

    best_x = None
    best_ub = np.inf
    best_start = None
    statuses = []
    attempts = 0

    t0_all = time.time()

    for start_name, x0 in starts:
        attempts += 1

        problem_obj = IpoptQPLIBProblem(data)

        nlp = cyipopt.Problem(
            n=n,
            m=m,
            problem_obj=problem_obj,
            lb=data["l"],
            ub=data["u"],
            cl=cl,
            cu=cu,
        )

        nlp.add_option("print_level", 0)
        nlp.add_option("max_iter", int(IPOPT_MAX_ITER))
        nlp.add_option("tol", float(IPOPT_TOL))
        nlp.add_option("constr_viol_tol", float(IPOPT_CONSTR_VIOL_TOL))
        nlp.add_option("max_cpu_time", float(IPOPT_TIME_LIMIT_PER_START))
        nlp.add_option("hessian_approximation", "limited-memory")
        nlp.add_option("mu_strategy", "adaptive")

        t0 = time.time()

        try:
            x_sol, info = nlp.solve(np.asarray(x0, dtype=float))
            runtime = time.time() - t0

            status = info.get("status", None)
            obj_ipopt = float(info.get("obj_val", np.nan))
            check = check_feasibility(data, x_sol)

            statuses.append(
                f"{start_name}:status={status},obj={obj_ipopt:.8g},"
                f"feas={check['is_feasible']},"
                f"viol={check['max_constraint_violation']:.2e},"
                f"t={runtime:.2f}"
            )

            # Important: accept ONLY the result of our own manual check.
            if check["is_feasible"]:
                ub = objective_value(data, x_sol)
                if ub < best_ub:
                    best_ub = float(ub)
                    best_x = np.asarray(x_sol, dtype=float)
                    best_start = start_name

        except Exception as e:
            runtime = time.time() - t0
            statuses.append(
                f"{start_name}:error={type(e).__name__}:{str(e)},t={runtime:.2f}"
            )

    return {
        "best_x": best_x,
        "best_ub": best_ub,
        "best_start": best_start,
        "attempts": attempts,
        "status_summary": " | ".join(statuses)[:4000],
        "runtime": time.time() - t0_all,
    }


def add_qexpr_gurobi_qplib(x_vars, A, b, c, tol=0.0):
    """
    Build:
        0.5*x^T A*x + b^T*x + c

    We loop only over nonzero entries for speed.
    """
    expr = gp.QuadExpr()
    expr.add(float(c))

    b = np.asarray(b, dtype=float)
    for i in np.where(np.abs(b) > tol)[0]:
        expr.add(float(b[i]) * x_vars[int(i)])

    A = np.asarray(A, dtype=float)
    nz = np.argwhere(np.abs(A) > tol)
    for i, j in nz:
        expr.add(0.5 * float(A[i, j]) * x_vars[int(i)] * x_vars[int(j)])

    return expr


def solve_gurobi_repair_qplib(data):
    if not HAS_GUROBI or not RUN_GUROBI_REPAIR_FALLBACK:
        return {
            "has_solution": False,
            "x": None,
            "ub": np.inf,
            "status": "gurobi_not_available_or_disabled",
            "slack_sum": np.inf,
            "runtime": 0.0,
        }

    n = data["n"]
    m = data["m_solver"]

    model = gp.Model(f"qplib_repair_{data['name']}")
    model.Params.OutputFlag = 0
    model.Params.TimeLimit = float(GUROBI_REPAIR_TIME_LIMIT)
    model.Params.NonConvex = 2

    x = [
        model.addVar(
            lb=float(data["l"][i]),
            ub=float(data["u"][i]),
            vtype=GRB.CONTINUOUS,
            name=f"x[{i}]",
        )
        for i in range(n)
    ]

    s = [
        model.addVar(lb=0.0, vtype=GRB.CONTINUOUS, name=f"s[{k}]")
        for k in range(1, m + 1)
    ]

    model.update()

    for k in range(1, m + 1):
        qk = add_qexpr_gurobi_qplib(
            x,
            data["A_list"][k],
            data["b_list"][k],
            data["c_list"][k],
        )
        model.addQConstr(qk <= s[k - 1], name=f"repair_qc[{k}]")

    model.setObjective(gp.quicksum(s), GRB.MINIMIZE)

    t0 = time.time()
    model.optimize()
    runtime = time.time() - t0

    if model.SolCount == 0:
        return {
            "has_solution": False,
            "x": None,
            "ub": np.inf,
            "status": f"gurobi_status_{model.Status}",
            "slack_sum": np.inf,
            "runtime": runtime,
        }

    x_val = np.array([var.X for var in x], dtype=float)
    slack_sum = float(sum(sk.X for sk in s))

    check = check_feasibility(data, x_val)
    ub = objective_value(data, x_val) if check["is_feasible"] else np.inf

    return {
        "has_solution": True,
        "x": x_val,
        "ub": float(ub),
        "status": f"gurobi_status_{model.Status}",
        "slack_sum": slack_sum,
        "runtime": runtime,
        "check": check,
    }


def load_existing_feasible_points():
    points = {}
    old_df = pd.DataFrame()

    if RESUME_FEASIBLE_SEARCH and QPLIB_FEASIBLE_PKL.exists():
        try:
            with open(QPLIB_FEASIBLE_PKL, "rb") as f:
                points = pickle.load(f)
            if not isinstance(points, dict):
                points = {}
        except Exception:
            points = {}

    if RESUME_FEASIBLE_SEARCH and QPLIB_FEASIBLE_CSV.exists():
        try:
            old_df = pd.read_csv(QPLIB_FEASIBLE_CSV)
        except Exception:
            old_df = pd.DataFrame()

    return points, old_df


def run_qplib_feasible_search(pkl_files):
    feasible_points, old_df = load_existing_feasible_points()

    completed = set()
    if not old_df.empty and "name" in old_df.columns:
        completed = set(old_df["name"].astype(str))

    rows = old_df.to_dict("records") if not old_df.empty else []

    for idx, pkl_path in enumerate(pkl_files):
        data = load_qplib_pickle(pkl_path)
        name = str(data["name"])

        if RESUME_FEASIBLE_SEARCH and name in completed:
            print(f"[{idx+1}/{len(pkl_files)}] {name}: already processed -> skip")
            continue

        print(f"\n[{idx+1}/{len(pkl_files)}] {name} | n={data['n']} m={data['m_solver']}")

        starts = make_start_points(
            data["l"],
            data["u"],
            n_random=N_RANDOM_STARTS,
            seed=RANDOM_SEED + idx,
        )

        ipopt_res = solve_with_ipopt_qplib(data, starts)

        chosen_x = None
        chosen_ub = np.inf
        chosen_source = None
        repair_res = None

        if ipopt_res["best_x"] is not None and np.isfinite(ipopt_res["best_ub"]):
            chosen_x = np.asarray(ipopt_res["best_x"], dtype=float)
            chosen_ub = float(ipopt_res["best_ub"])
            chosen_source = f"ipopt:{ipopt_res['best_start']}"
        elif RUN_GUROBI_REPAIR_FALLBACK:
            repair_res = solve_gurobi_repair_qplib(data)
            if (
                repair_res.get("x") is not None
                and np.isfinite(repair_res.get("ub", np.inf))
            ):
                chosen_x = np.asarray(repair_res["x"], dtype=float)
                chosen_ub = float(repair_res["ub"])
                chosen_source = "gurobi_repair"

        if chosen_x is not None:
            check = check_feasibility(data, chosen_x)
            accepted = bool(check["is_feasible"])
        else:
            check = {
                "is_feasible": False,
                "max_bound_violation": np.nan,
                "max_constraint_violation": np.nan,
            }
            accepted = False

        row = {
            "name": name,
            "file": pkl_path.name,
            "probtype": data["probtype"],
            "n": data["n"],
            "m_solver": data["m_solver"],
            "integrality_relaxed": data["integrality_relaxed"],
            "accepted": accepted,
            "ub": chosen_ub if accepted else np.nan,
            "source": chosen_source,
            "max_bound_violation": check["max_bound_violation"],
            "max_constraint_violation": check["max_constraint_violation"],
            "ipopt_attempts": ipopt_res["attempts"],
            "ipopt_runtime": ipopt_res["runtime"],
            "ipopt_status_summary": ipopt_res["status_summary"],
            "gurobi_repair_status": (
                repair_res.get("status") if repair_res is not None else None
            ),
            "gurobi_repair_slack_sum": (
                repair_res.get("slack_sum") if repair_res is not None else np.nan
            ),
            "gurobi_repair_runtime": (
                repair_res.get("runtime") if repair_res is not None else 0.0
            ),
        }

        rows.append(row)

        if accepted:
            feasible_points[name] = {
                "name": name,
                "file": pkl_path.name,
                "x": chosen_x,
                "ub": float(chosen_ub),
                "source": chosen_source,
                "max_bound_violation": check["max_bound_violation"],
                "max_constraint_violation": check["max_constraint_violation"],
            }

        # Checkpoint after EVERY instance.
        pd.DataFrame(rows).drop_duplicates(
            subset=["name"], keep="last"
        ).to_csv(QPLIB_FEASIBLE_CSV, index=False)

        with open(QPLIB_FEASIBLE_PKL, "wb") as f:
            pickle.dump(feasible_points, f)

        print(
            "accepted =", accepted,
            "| source =", chosen_source,
            "| UB =", chosen_ub if accepted else None,
        )

        gc.collect()

    final_df = pd.DataFrame(rows).drop_duplicates(
        subset=["name"], keep="last"
    ).reset_index(drop=True)

    final_df.to_csv(QPLIB_FEASIBLE_CSV, index=False)
    with open(QPLIB_FEASIBLE_PKL, "wb") as f:
        pickle.dump(feasible_points, f)

    print("\nFeasible incumbent summary")
    print(final_df["accepted"].value_counts(dropna=False))
    print("Saved:", QPLIB_FEASIBLE_CSV)
    print("Saved:", QPLIB_FEASIBLE_PKL)

    return final_df, feasible_points


# RUN THIS CELL TO GENERATE / RESUME FEASIBLE INCUMBENTS.
qplib_feasible_df, qplib_feasible_points = run_qplib_feasible_search(pkl_files)

display(qplib_feasible_df.head())

[1/143] QPLIB_0018 | n=50 m=2
accepted = True | source = ipopt:clipped_zero | UB = -6.386018862109888

[2/143] QPLIB_0031 | n=60 m=33
accepted = True | source = ipopt:clipped_zero | UB = 15.20052472562084

[3/143] QPLIB_0032 | n=100 m=53
accepted = True | source = ipopt:clipped_zero | UB = 9.94558798396219

[4/143] QPLIB_0067 | n=80 m=1
accepted = True | source = ipopt:clipped_zero | UB = -112205.36058245547

[5/143] QPLIB_0343 | n=50 m=2
accepted = True | source = ipopt:clipped_zero | UB = -6.386018862109817

[6/143] QPLIB_0633 | n=75 m=2
accepted = True | source = ipopt:random_0 | UB = 79.57916821078919

[7/143] QPLIB_0681 | n=215 m=538
accepted = True | source = ipopt:random_0 | UB = -48.26342933984606

[8/143] QPLIB_0682 | n=261 m=716
accepted = True | source = ipopt:random_2 | UB = -48.04304402260596

[9/143] QPLIB_0698 | n=118 m=157
accepted = True | source = ipopt:random_3 | UB = 968572.1425647809

[10/143] QPLIB_0752 | n=250 m=1
accepted = True | source = ipopt:lower_25pct | UB = -24022.00067618385

[11/143] QPLIB_0911 | n=50 m=50
accepted = True | source = ipopt:lower_25pct | UB = -32.147559336066074

[12/143] QPLIB_0975 | n=50 m=10
accepted = True | source = ipopt:random_4 | UB = -37.63524204149308

[13/143] QPLIB_10010 | n=269 m=148
accepted = True | source = ipopt:midpoint | UB = -23301.342740094344

[14/143] QPLIB_10040 | n=125 m=6
accepted = True | source = ipopt:random_0 | UB = 5.488349257122234e-10

[15/143] QPLIB_10041 | n=125 m=6
accepted = True | source = ipopt:random_4 | UB = -3.5130793444107e-10

[16/143] QPLIB_10042 | n=125 m=5
accepted = True | source = ipopt:random_0 | UB = -22.164986933085512

[17/143] QPLIB_10043 | n=150 m=10
accepted = True | source = ipopt:random_0 | UB = 6.46091397428678e-08

[18/143] QPLIB_10044 | n=150 m=6
accepted = True | source = ipopt:random_2 | UB = -10.636739823847371

[19/143] QPLIB_10045 | n=150 m=10
accepted = True | source = ipopt:random_4 | UB = 3.155626849009839e-10

[20/143] QPLIB_10046 | n=150 m=6
accepted = True | source = ipopt:random_0 | UB = -3.3404918519857283

[21/143] QPLIB_10047 | n=150 m=10
accepted = True | source = ipopt:random_3 | UB = -4.014814198600539e-10

[22/143] QPLIB_10048 | n=150 m=5
accepted = True | source = ipopt:midpoint | UB = -17.546486847063

[23/143] QPLIB_10049 | n=150 m=10
accepted = True | source = ipopt:random_2 | UB = -3.135393239991966e-10

[24/143] QPLIB_10050 | n=150 m=5
accepted = True | source = ipopt:lower_25pct | UB = -27.38233232171629

[25/143] QPLIB_10051 | n=150 m=10
accepted = True | source = ipopt:random_0 | UB = -1.9150909375617823e-10

[26/143] QPLIB_10052 | n=150 m=6
accepted = True | source = ipopt:random_4 | UB = -14.508618310532233

[27/143] QPLIB_10053 | n=150 m=10
accepted = True | source = ipopt:random_1 | UB = 2.029266519396541e-09

[28/143] QPLIB_10054 | n=175 m=11
accepted = True | source = ipopt:random_4 | UB = -15.208407563975834

[29/143] QPLIB_10055 | n=175 m=5
accepted = True | source = ipopt:lower_25pct | UB = -5.032666667396788

[30/143] QPLIB_10056 | n=175 m=5
accepted = True | source = ipopt:clipped_zero | UB = -35.32453001342119

[31/143] QPLIB_10057 | n=200 m=11
accepted = True | source = ipopt:lower_25pct | UB = 1.5979470266341675e-06

[32/143] QPLIB_10058 | n=200 m=11
accepted = True | source = ipopt:midpoint | UB = -8.210941777955203

[33/143] QPLIB_10059 | n=200 m=10
accepted = True | source = ipopt:random_0 | UB = -3.256540765741755e-09

[34/143] QPLIB_10060 | n=200 m=10
accepted = True | source = ipopt:random_4 | UB = 8.332617257439004e-07

[35/143] QPLIB_10061 | n=200 m=5
accepted = True | source = ipopt:random_4 | UB = -25.67957055436643

[36/143] QPLIB_10062 | n=200 m=10
accepted = True | source = ipopt:clipped_zero | UB = 9.544373704517251e-10

[37/143] QPLIB_10063 | n=200 m=5
accepted = True | source = ipopt:upper_75pct | UB = -42.77722346226982

[38/143] QPLIB_10064 | n=200 m=11
accepted = True | source = ipopt:lower_25pct | UB = 1.0390964719081366e-09

[39/143] QPLIB_10065 | n=200 m=11
accepted = True | source = ipopt:random_0 | UB = -31.173824712687285

[40/143] QPLIB_10066 | n=200 m=11
accepted = True | source = ipopt:clipped_zero | UB = -34.09306838403337

[41/143] QPLIB_10067 | n=200 m=5
accepted = True | source = ipopt:random_2 | UB = -34.28577474649638

[42/143] QPLIB_10068 | n=200 m=11
accepted = True | source = ipopt:random_1 | UB = -33.53145899902923

[43/143] QPLIB_10069 | n=200 m=10
accepted = True | source = ipopt:midpoint | UB = 1.0291185994973794e-09

[44/143] QPLIB_10070 | n=200 m=11
accepted = True | source = ipopt:random_1 | UB = -28.30224248743339

[45/143] QPLIB_10071 | n=200 m=11
accepted = True | source = ipopt:upper_75pct | UB = 5.393647172299134e-06

[46/143] QPLIB_10072 | n=75 m=10
accepted = True | source = ipopt:random_1 | UB = 9.742228791796426e-10

[47/143] QPLIB_10073 | n=75 m=6
accepted = True | source = ipopt:random_2 | UB = -5.322677043344818e-10

[48/143] QPLIB_10074 | n=75 m=10
accepted = True | source = ipopt:lower_25pct | UB = 3.0743623492100146e-10

[49/143] QPLIB_1055 | n=40 m=20
accepted = True | source = ipopt:random_0 | UB = -33.03702417773977

[50/143] QPLIB_1143 | n=40 m=28
accepted = True | source = ipopt:midpoint | UB = -56.23646449071677

[51/143] QPLIB_1157 | n=40 m=17
accepted = True | source = ipopt:lower_25pct | UB = -10.948204143609978

[52/143] QPLIB_1353 | n=50 m=11
accepted = True | source = ipopt:upper_75pct | UB = -7.714162600856687

[53/143] QPLIB_1423 | n=40 m=28
accepted = True | source = ipopt:random_4 | UB = -14.967468073912471

[54/143] QPLIB_1437 | n=50 m=21
accepted = True | source = ipopt:random_4 | UB = -7.78917325866677

[55/143] QPLIB_1451 | n=60 m=72
accepted = True | source = ipopt:random_1 | UB = -87.57648915706348

[56/143] QPLIB_1493 | n=40 m=9
accepted = True | source = ipopt:random_0 | UB = -42.40751719914804

[57/143] QPLIB_1507 | n=30 m=36
accepted = True | source = ipopt:random_4 | UB = -8.30137713948833

[58/143] QPLIB_1535 | n=60 m=72
accepted = True | source = ipopt:random_4 | UB = -11.549995494980633

[59/143] QPLIB_1619 | n=50 m=35
accepted = True | source = ipopt:midpoint | UB = -9.217302762695287

[60/143] QPLIB_1661 | n=60 m=25
accepted = True | source = ipopt:clipped_zero | UB = -15.954898272408581

[61/143] QPLIB_1675 | n=60 m=25
accepted = True | source = ipopt:random_3 | UB = -75.66868498553237

[62/143] QPLIB_1703 | n=60 m=42
accepted = True | source = ipopt:midpoint | UB = -132.38056879507607

[63/143] QPLIB_1745 | n=50 m=60
accepted = True | source = ipopt:midpoint | UB = -72.3765923259007

[64/143] QPLIB_1773 | n=60 m=13
accepted = True | source = ipopt:random_2 | UB = -14.641861749468891

[65/143] QPLIB_1886 | n=50 m=50
accepted = True | source = ipopt:random_1 | UB = -78.67156373196862

[66/143] QPLIB_1913 | n=48 m=48
accepted = True | source = ipopt:lower_25pct | UB = -51.8892840941836

[67/143] QPLIB_1922 | n=30 m=60
accepted = True | source = ipopt:lower_25pct | UB = -35.74115523288518

[68/143] QPLIB_1931 | n=40 m=40
accepted = True | source = ipopt:random_3 | UB = -55.7088768267314

[69/143] QPLIB_1940 | n=48 m=96
accepted = True | source = ipopt:midpoint | UB = -38.31010935939475

[70/143] QPLIB_1967 | n=50 m=75
accepted = True | source = ipopt:lower_25pct | UB = -106.90969795756523

[71/143] QPLIB_1976 | n=152 m=168
accepted = True | source = ipopt:clipped_zero | UB = -13126.257674799475

[72/143] QPLIB_2017 | n=252 m=273
accepted = True | source = ipopt:clipped_zero | UB = -24629.757123197185

[73/143] QPLIB_2022 | n=275 m=297
accepted = True | source = ipopt:random_1 | UB = -23012.799187887165

[74/143] QPLIB_2029 | n=299 m=322
accepted = True | source = ipopt:midpoint | UB = -35025.71099049719

[75/143] QPLIB_2047 | n=136 m=2057
accepted = True | source = ipopt:random_1 | UB = 1120992.0699590633

[76/143] QPLIB_2055 | n=153 m=2466
accepted = True | source = ipopt:random_3 | UB = 3240624.542415875

[77/143] QPLIB_2060 | n=171 m=2926
accepted = True | source = ipopt:midpoint | UB = 2488112.1976658693

[78/143] QPLIB_2067 | n=190 m=3440
accepted = True | source = ipopt:lower_25pct | UB = 3098850.009597823

[79/143] QPLIB_2073 | n=210 m=4011
accepted = True | source = ipopt:lower_25pct | UB = 9093047.863001555

[80/143] QPLIB_2077 | n=231 m=4642
accepted = True | source = ipopt:lower_25pct | UB = 2838692.7226712704

[81/143] QPLIB_2085 | n=253 m=5336
accepted = True | source = ipopt:upper_75pct | UB = 9573255.0

[82/143] QPLIB_2087 | n=276 m=6096
accepted = True | source = ipopt:midpoint | UB = 10756299.5

[83/143] QPLIB_2353 | n=240 m=2240
accepted = True | source = ipopt:random_0 | UB = -670.781583884825

[84/143] QPLIB_2357 | n=240 m=2240
accepted = True | source = ipopt:random_1 | UB = -171.70042938752462

[85/143] QPLIB_2416 | n=25 m=692
Set parameter Username
Academic license - for non-commercial use only - expires 2027-09-30
accepted = False | source = None | UB = None

[86/143] QPLIB_2430 | n=125 m=184
accepted = True | source = ipopt:random_3 | UB = -1.9727907369647177

[87/143] QPLIB_2445 | n=143 m=142
accepted = True | source = ipopt:random_3 | UB = 327.51861860211375

[88/143] QPLIB_2492 | n=196 m=56
accepted = True | source = ipopt:clipped_zero | UB = 2656.5534547215475

[89/143] QPLIB_2512 | n=100 m=40
accepted = True | source = ipopt:random_2 | UB = 130869.65135030047

[90/143] QPLIB_2590 | n=25 m=500
accepted = False | source = None | UB = None

[91/143] QPLIB_2658 | n=184 m=345
accepted = True | source = ipopt:midpoint | UB = 9.247589155475854

[92/143] QPLIB_2698 | n=196 m=93
accepted = True | source = ipopt:clipped_zero | UB = 1201.0384691508143

[93/143] QPLIB_2702 | n=260 m=247
accepted = True | source = ipopt:clipped_zero | UB = 1415.2479384604778

[94/143] QPLIB_2712 | n=200 m=2
accepted = True | source = ipopt:midpoint | UB = 0.012866898159838557

[95/143] QPLIB_2738 | n=199 m=299
accepted = True | source = ipopt:midpoint | UB = -4.284199092354807

[96/143] QPLIB_2834 | n=156 m=160
accepted = True | source = ipopt:upper_75pct | UB = 365.78360494774915

[97/143] QPLIB_2894 | n=17 m=213
accepted = True | source = gurobi_repair | UB = 5.999999999094884

[98/143] QPLIB_2987 | n=208 m=396
accepted = True | source = gurobi_repair | UB = 5078.418363482791

[99/143] QPLIB_2993 | n=266 m=614
accepted = True | source = gurobi_repair | UB = 9350.067150748931

[100/143] QPLIB_3083 | n=243 m=452
accepted = True | source = gurobi_repair | UB = 5096.612264073573

[101/143] QPLIB_3089 | n=132 m=168
accepted = True | source = ipopt:random_0 | UB = 312.9215388237215

[102/143] QPLIB_3225 | n=136 m=142
accepted = True | source = ipopt:random_4 | UB = 511.5272413735418

[103/143] QPLIB_3307 | n=256 m=64
accepted = True | source = ipopt:random_1 | UB = 1224.2498706389401

[104/143] QPLIB_3318 | n=25 m=480
accepted = False | source = None | UB = None

[105/143] QPLIB_3358 | n=158 m=317
accepted = True | source = ipopt:random_4 | UB = 3.0971140908962935

[106/143] QPLIB_3385 | n=155 m=268
accepted = True | source = ipopt:clipped_zero | UB = 12724.687479411721

[107/143] QPLIB_3387 | n=170 m=141
accepted = True | source = ipopt:random_1 | UB = 403.1959735137361

[108/143] QPLIB_3402 | n=144 m=48
accepted = True | source = ipopt:lower_25pct | UB = 220075.07162054942

[109/143] QPLIB_3512 | n=191 m=474
accepted = True | source = ipopt:upper_75pct | UB = -48.39060141352462

[110/143] QPLIB_3523 | n=182 m=1456
accepted = True | source = ipopt:random_3 | UB = -583.5013350752154

[111/143] QPLIB_3562 | n=63 m=42
accepted = True | source = ipopt:random_4 | UB = 13.650696060036072

[112/143] QPLIB_3587 | n=240 m=76
accepted = True | source = ipopt:upper_75pct | UB = 15284.966894919105

[113/143] QPLIB_3614 | n=210 m=74
accepted = True | source = ipopt:upper_75pct | UB = 14229.626766809966

[114/143] QPLIB_3703 | n=225 m=60
accepted = True | source = ipopt:random_1 | UB = 383597.4852916146

[115/143] QPLIB_3714 | n=120 m=80
accepted = True | source = ipopt:random_4 | UB = 1182.9998341260907

[116/143] QPLIB_3750 | n=210 m=140
accepted = True | source = ipopt:random_4 | UB = 6347.999110854607

[117/143] QPLIB_3751 | n=150 m=100
accepted = True | source = ipopt:random_1 | UB = 2311.9996760270133

[118/143] QPLIB_3762 | n=90 m=480
accepted = True | source = ipopt:lower_25pct | UB = -296.0000110567001

[119/143] QPLIB_3775 | n=180 m=120
accepted = True | source = ipopt:random_1 | UB = 3989.9994398232066

[120/143] QPLIB_3780 | n=168 m=72
accepted = True | source = ipopt:lower_25pct | UB = 85.35458328694021

[121/143] QPLIB_3790 | n=195 m=378
accepted = True | source = ipopt:clipped_zero | UB = 0.018209316176226887

[122/143] QPLIB_3803 | n=190 m=2280
accepted = True | source = ipopt:clipped_zero | UB = 3592.034861644446

[123/143] QPLIB_3814 | n=48 m=80
accepted = True | source = ipopt:random_1 | UB = 0.5555350438242206

[124/143] QPLIB_3815 | n=192 m=128
accepted = True | source = ipopt:random_3 | UB = -64.00000263779087

[125/143] QPLIB_3816 | n=187 m=434
accepted = True | source = ipopt:random_3 | UB = -21.8766011424702

[126/143] QPLIB_3834 | n=50 m=2
accepted = True | source = ipopt:lower_25pct | UB = 3872.764645000217

[127/143] QPLIB_3870 | n=182 m=1456
accepted = True | source = ipopt:random_0 | UB = -1053.7704991210446

[128/143] QPLIB_3883 | n=182 m=1456
accepted = True | source = ipopt:random_3 | UB = -728.7839141015444

[129/143] QPLIB_3980 | n=235 m=96
accepted = True | source = ipopt:lower_25pct | UB = -2.858708593160145

[130/143] QPLIB_5935 | n=100 m=1237
accepted = True | source = ipopt:lower_25pct | UB = -34295.75067481509

[131/143] QPLIB_5944 | n=100 m=2475
accepted = True | source = ipopt:random_3 | UB = -34173.74998223763

[132/143] QPLIB_5962 | n=150 m=2793
accepted = True | source = ipopt:midpoint | UB = -75551.3600403882

[133/143] QPLIB_5971 | n=150 m=5587
accepted = True | source = ipopt:midpoint | UB = -75524.5

[134/143] QPLIB_5980 | n=150 m=8381
accepted = True | source = ipopt:midpoint | UB = -75351.92800979952

[135/143] QPLIB_6287 | n=171 m=144
accepted = True | source = ipopt:clipped_zero | UB = -2410.6879703178274

[136/143] QPLIB_6310 | n=208 m=562
accepted = True | source = ipopt:random_1 | UB = -689.1604465610691

[137/143] QPLIB_6311 | n=212 m=211
accepted = True | source = ipopt:random_4 | UB = -4539.91268180354

[138/143] QPLIB_7139 | n=180 m=200
accepted = True | source = ipopt:random_3 | UB = 620.9997863375115

[139/143] QPLIB_7144 | n=220 m=242
accepted = True | source = ipopt:random_4 | UB = 812.9996581884146

[140/143] QPLIB_7149 | n=264 m=288
accepted = True | source = ipopt:upper_75pct | UB = 1000.9994920702003

[141/143] QPLIB_8153 | n=124 m=160
accepted = True | source = ipopt:random_1 | UB = -1.0763520567816882

[142/143] QPLIB_8381 | n=204 m=260
accepted = True | source = ipopt:clipped_zero | UB = -1.1057569213920344

[143/143] QPLIB_9048 | n=202 m=2
accepted = True | source = ipopt:lower_25pct | UB = -1.3966212732676924

Feasible incumbent summary
accepted
True     140
False      3
Name: count, dtype: int64
Saved: C:\Users\suuser\Desktop\minlplib\Areview\qplib\bb_qplib\qplib_feasible_ubs.csv
Saved: C:\Users\suuser\Desktop\minlplib\Areview\qplib\bb_qplib\qplib_feasible_points.pkl

,name,file,probtype,n,m_solver,integrality_relaxed,accepted,ub,source,max_bound_violation,max_constraint_violation,ipopt_attempts,ipopt_runtime,ipopt_status_summary,gurobi_repair_status,gurobi_repair_slack_sum,gurobi_repair_runtime
0,QPLIB_0018,QPLIB_0018.pkl,QCL,50,2,True,True,-6.386019,ipopt:clipped_zero,9.999521e-09,9.999217e-09,9,0.465332,"midpoint:status=0,obj=-6.3860189,feas=True,vio...",None,NaN,0.0
1,QPLIB_0031,QPLIB_0031.pkl,QML,60,33,True,True,15.200525,ipopt:clipped_zero,9.999999e-09,9.999671e-09,9,4.620625,"midpoint:status=0,obj=15.200525,feas=True,viol...",None,NaN,0.0
2,QPLIB_0032,QPLIB_0032.pkl,QML,100,53,True,True,9.945588,ipopt:clipped_zero,9.999997e-09,9.999497e-09,9,55.637327,"midpoint:status=1,obj=9.9455887,feas=True,viol...",None,NaN,0.0
3,QPLIB_0067,QPLIB_0067.pkl,QBL,80,1,True,True,-112205.360582,ipopt:clipped_zero,9.999997e-09,9.999894e-09,9,0.300198,"midpoint:status=0,obj=-112205.36,feas=True,vio...",None,NaN,0.0
4,QPLIB_0343,QPLIB_0343.pkl,QCL,50,2,True,True,-6.386019,ipopt:clipped_zero,9.999521e-09,9.999217e-09,9,0.470000,"midpoint:status=0,obj=-6.3860189,feas=True,vio...",None,NaN,0.0

In [7]:

# ============================================================
# 4. QPLIB B&B DATA GENERATOR
# Separate LP and SDP' trees.
# Sequential branching is intentionally preserved.
# ============================================================

@dataclass
class Node:
    node_id: int
    parent_id: Optional[int]
    depth: int
    l_bounds: np.ndarray
    u_bounds: np.ndarray
    branch_var: Optional[int] = None
    split_point: Optional[float] = None

    lp_obj: Optional[float] = None
    lp_time: Optional[float] = None
    lp_status: Optional[str] = None

    sdpp_obj: Optional[float] = None
    sdpp_time: Optional[float] = None
    sdpp_status: Optional[str] = None

    status: str = "pending"
    note: Optional[str] = None

    inherited_lb: Optional[float] = None
    known_lb: Optional[float] = None


def select_branch_variable(node: Node, min_width=MIN_WIDTH) -> Optional[int]:
    """
    Preserve the MINLPLib sequential rule.

    Start from depth % n.
    If that variable is fixed / too narrow, scan forward to the next
    branchable variable. We do NOT introduce a new branching heuristic here.
    """
    n = len(node.l_bounds)
    start = node.depth % n

    for offset in range(n):
        j = (start + offset) % n
        width = float(node.u_bounds[j] - node.l_bounds[j])

        if np.isfinite(width) and width > min_width:
            return int(j)

    return None


def create_children(parent: Node, branch_var: int, next_node_id: int):
    l = parent.l_bounds.copy()
    u = parent.u_bounds.copy()

    split = 0.5 * (float(l[branch_var]) + float(u[branch_var]))

    u_left = u.copy()
    u_left[branch_var] = split

    left = Node(
        node_id=next_node_id,
        parent_id=parent.node_id,
        depth=parent.depth + 1,
        l_bounds=l.copy(),
        u_bounds=u_left,
        branch_var=branch_var,
        split_point=split,
        inherited_lb=parent.known_lb,
        known_lb=parent.known_lb,
    )

    l_right = l.copy()
    l_right[branch_var] = split

    right = Node(
        node_id=next_node_id + 1,
        parent_id=parent.node_id,
        depth=parent.depth + 1,
        l_bounds=l_right,
        u_bounds=u.copy(),
        branch_var=branch_var,
        split_point=split,
        inherited_lb=parent.known_lb,
        known_lb=parent.known_lb,
    )

    return left, right


def solve_relaxation_at_node(data, node, relaxation):
    solver = QCQPSolver(
        A_list=data["A_list"],
        b_list=data["b_list"],
        c_list=data["c_list"],
        l=node.l_bounds,
        u=node.u_bounds,
        use_blocks=USE_BLOCKS,
        block_tol=BLOCK_TOL,
        verbose_blocks=VERBOSE_BLOCKS,
        prune_matrices=PRUNE_MATRICES,
        min_block_edges=MIN_BLOCK_EDGES,
    )

    if relaxation == "LP":
        if hasattr(solver, "solve_lp"):
            res = solver.solve_lp()
        else:
            res = solver.solve("LP")

    elif relaxation == "SDP_PRIME":
        if hasattr(solver, "solve_sdp_prime"):
            res = solver.solve_sdp_prime()
        else:
            res = solver.solve("SDP_PRIME")

    else:
        raise ValueError(relaxation)

    obj = res.get("objective")
    solve_time = res.get("time")
    solve_status = res.get("status")

    if relaxation == "LP":
        node.lp_obj = obj
        node.lp_time = solve_time
        node.lp_status = solve_status
    else:
        node.sdpp_obj = obj
        node.sdpp_time = solve_time
        node.sdpp_status = solve_status

    if solve_status is None:
        node.status = "error"
        node.note = "Missing solve status"
        return node

    s = str(solve_status).lower().strip()

    # This reproduces the MINLPLib B&B treatment.
    if s == "gurobi_status_4":
        node.status = "infeasible"
        node.note = (
            "Gurobi INF_OR_UNBD status 4 treated as infeasible "
            "because finite x bounds + McCormick envelopes make the LP node bounded."
        )
    elif "infeas" in s:
        node.status = "infeasible"
    elif "unknown" in s:
        node.status = "unknown"
        node.note = f"Unresolved solver status: {solve_status}"
    elif "unbound" in s:
        node.status = "unbounded"
        node.note = f"Unexpected unbounded solver status: {solve_status}"
    elif "error" in s or "exception" in s:
        node.status = "error"
        node.note = f"Solver error status: {solve_status}"
    elif "optimal" in s:
        node.status = "processed"
    else:
        node.status = "error"
        node.note = f"Unexpected solver status: {solve_status}"

    return node


def node_obj(node, relaxation):
    return node.lp_obj if relaxation == "LP" else node.sdpp_obj


def compute_global_frontier_lb(queue, open_terminal_nodes, closed_by_bound_lbs):
    represented_lbs = []

    for active_node in list(queue) + list(open_terminal_nodes.values()):
        if active_node.known_lb is None:
            return np.nan

        lb = float(active_node.known_lb)

        if np.isnan(lb):
            return np.nan

        represented_lbs.append(lb)

    represented_lbs.extend(float(lb) for lb in closed_by_bound_lbs)

    if represented_lbs:
        return float(min(represented_lbs))

    # Empty represented tree: do not substitute the incumbent UB as a lower bound.
    return np.nan


def run_tree(
    data,
    relaxation,
    shared_upper_bound,
    max_nodes,
    live_csv_path,
    instance_index,
    ub_info,
):
    node_counter = 0
    processed_count = 0
    had_unresolved_status = False

    open_terminal_nodes = {}
    closed_by_bound_lbs = []

    root = Node(
        node_id=node_counter,
        parent_id=None,
        depth=0,
        l_bounds=data["l"].copy(),
        u_bounds=data["u"].copy(),
    )
    node_counter += 1

    queue = deque([root])
    node_buffer = []
    all_nodes = []
    last_frontier_lb = np.nan

    def flush():
        nonlocal node_buffer

        if not node_buffer:
            return

        df = pd.DataFrame(node_buffer)
        exists = live_csv_path.exists()

        df.to_csv(
            live_csv_path,
            mode="a",
            header=not exists,
            index=False,
        )
        node_buffer = []

    while queue:
        if max_nodes is not None and processed_count >= max_nodes:
            break

        node = queue.popleft()

        try:
            node = solve_relaxation_at_node(data, node, relaxation)
        except Exception as e:
            node.status = "error"
            node.note = f"{type(e).__name__}: {e}"

        all_nodes.append(node)
        processed_count += 1

        obj = node_obj(node, relaxation)

        if node.status == "processed":
            if obj is None or not np.isfinite(float(obj)):
                node.status = "error"
                node.note = "Processed node has no finite relaxation objective."
            else:
                node.known_lb = float(obj)

        stop_tree = False

        if node.status in {"unknown", "unbounded", "error"}:
            open_terminal_nodes[node.node_id] = node
            had_unresolved_status = True
            stop_tree = True

        elif node.status == "infeasible":
            # Proven empty region.
            pass

        elif (
            node.known_lb is not None
            and np.isfinite(float(node.known_lb))
            and float(node.known_lb) >= float(shared_upper_bound) - PRUNE_TOL
        ):
            node.status = "pruned_by_bound"
            node.note = (
                f"LB={float(node.known_lb):.12g} >= "
                f"UB={float(shared_upper_bound):.12g} - tol={PRUNE_TOL:.3g}"
            )
            closed_by_bound_lbs.append(float(node.known_lb))

        elif node.depth >= MAX_DEPTH:
            open_terminal_nodes[node.node_id] = node

        else:
            branch_var = select_branch_variable(node, min_width=MIN_WIDTH)

            if branch_var is None:
                node.status = "pruned"
                node.note = "No branchable variable with positive finite width."
                open_terminal_nodes[node.node_id] = node

            else:
                left, right = create_children(
                    parent=node,
                    branch_var=branch_var,
                    next_node_id=node_counter,
                )
                node_counter += 2
                queue.append(left)
                queue.append(right)

        last_frontier_lb = compute_global_frontier_lb(
            queue,
            open_terminal_nodes,
            closed_by_bound_lbs,
        )

        row = {
            "dataset_name": "qplib_fixed100",
            "instance_index": instance_index,
            "instance_name": data["name"],
            "instance_id": data["instance_id"],
            "probtype": data["probtype"],
            "integrality_relaxed": data["integrality_relaxed"],
            "convex": data["convex"],
            "n": data["n"],
            "m_original": data["m_original"],
            "m_solver": data["m_solver"],

            "relaxation": relaxation,
            "node_id": node.node_id,
            "parent_id": node.parent_id,
            "depth": node.depth,
            "branch_var": node.branch_var,
            "split_point": node.split_point,

            "status": node.status,
            "note": node.note,
            "solve_status": (
                node.lp_status if relaxation == "LP" else node.sdpp_status
            ),
            "obj": obj,
            "solve_time": (
                node.lp_time if relaxation == "LP" else node.sdpp_time
            ),

            "processed_count": processed_count,
            "inherited_lb": node.inherited_lb,
            "known_lb": node.known_lb,
            "shared_upper_bound": shared_upper_bound,
            "ub_source": ub_info.get("source"),
            "ub_max_bound_violation": ub_info.get("max_bound_violation"),
            "ub_max_constraint_violation": ub_info.get("max_constraint_violation"),

            "global_frontier_lb_after_step": last_frontier_lb,
            "queue_count_after_step": len(queue),
            "open_terminal_count_after_step": len(open_terminal_nodes),
            "pruned_by_bound": node.status == "pruned_by_bound",

            "lp_node_budget": FIXED_NODES_LP,
            "sdpp_node_budget": FIXED_NODES_SDPP,
            "branch_rule": BRANCH_RULE,
            "split_rule": SPLIT_RULE,
            "coefficient_convention": "0.5*xTAx + bTx + c",
        }

        node_buffer.append(row)

        if len(node_buffer) >= FLUSH_EVERY_NODES:
            flush()

        if stop_tree:
            flush()
            break

    flush()

    return {
        "nodes": all_nodes,
        "had_unresolved_status": had_unresolved_status,
        "processed_nodes": processed_count,
        "final_frontier_lb": last_frontier_lb,
        "queue_remaining": len(queue),
    }


def clean_partial_bb_rows_if_resuming():
    """
    Completed instances are listed in QPLIB_BB_SUMMARY_CSV.

    If a crash occurred in the middle of an instance, remove LIVE rows for
    names not present in the completed summary before resuming.
    """
    if not RESUME_BB:
        return set()

    completed = set()

    if QPLIB_BB_SUMMARY_CSV.exists():
        summary = pd.read_csv(QPLIB_BB_SUMMARY_CSV)
        if "instance_name" in summary.columns:
            completed = set(summary["instance_name"].astype(str))

    if QPLIB_LIVE_CSV.exists():
        live = pd.read_csv(QPLIB_LIVE_CSV)

        if "instance_name" in live.columns:
            clean = live[live["instance_name"].astype(str).isin(completed)].copy()

            if len(clean) != len(live):
                print(
                    f"Resume cleanup: removed {len(live)-len(clean)} "
                    "partial LIVE rows from incomplete instances."
                )
                clean.to_csv(QPLIB_LIVE_CSV, index=False)

    return completed


def run_qplib_bb(pkl_files, feasible_points):
    QPLIB_BB_DIR.mkdir(parents=True, exist_ok=True)

    completed = clean_partial_bb_rows_if_resuming()

    if not RESUME_BB:
        for path in [
            QPLIB_LIVE_CSV,
            QPLIB_LIVE_PARQUET,
            QPLIB_BB_SUMMARY_CSV,
            QPLIB_BB_SKIPPED_CSV,
        ]:
            if path.exists():
                path.unlink()

    summary_rows = []
    skipped_rows = []

    if QPLIB_BB_SUMMARY_CSV.exists() and RESUME_BB:
        summary_rows = pd.read_csv(QPLIB_BB_SUMMARY_CSV).to_dict("records")

    if QPLIB_BB_SKIPPED_CSV.exists() and RESUME_BB:
        skipped_rows = pd.read_csv(QPLIB_BB_SKIPPED_CSV).to_dict("records")

    for idx, pkl_path in enumerate(pkl_files):
        data = load_qplib_pickle(pkl_path)
        name = str(data["name"])

        if RESUME_BB and name in completed:
            print(f"[{idx+1}/{len(pkl_files)}] {name}: already complete -> skip")
            continue

        print(
            f"\n[{idx+1}/{len(pkl_files)}] {name} "
            f"| n={data['n']} m={data['m_solver']}"
        )

        ub_info = feasible_points.get(name)

        if (
            ub_info is None
            or ub_info.get("x") is None
            or ub_info.get("ub") is None
            or not np.isfinite(float(ub_info["ub"]))
        ):
            skipped_rows.append({
                "instance_name": name,
                "file": pkl_path.name,
                "reason": "no_verified_feasible_incumbent",
            })
            pd.DataFrame(skipped_rows).drop_duplicates(
                subset=["instance_name"], keep="last"
            ).to_csv(QPLIB_BB_SKIPPED_CSV, index=False)

            print("SKIPPED: no verified feasible incumbent.")
            continue

        # Revalidate before using the point for pruning.
        check = check_feasibility(data, ub_info["x"])

        if not check["is_feasible"]:
            skipped_rows.append({
                "instance_name": name,
                "file": pkl_path.name,
                "reason": "stored_incumbent_failed_revalidation",
                "max_bound_violation": check["max_bound_violation"],
                "max_constraint_violation": check["max_constraint_violation"],
            })
            pd.DataFrame(skipped_rows).drop_duplicates(
                subset=["instance_name"], keep="last"
            ).to_csv(QPLIB_BB_SKIPPED_CSV, index=False)

            print("SKIPPED: incumbent failed revalidation.")
            continue

        shared_ub = objective_value(data, ub_info["x"])

        print(
            f"Incumbent UB={shared_ub:.12g} "
            f"| source={ub_info.get('source')}"
        )

        lp = run_tree(
            data=data,
            relaxation="LP",
            shared_upper_bound=shared_ub,
            max_nodes=FIXED_NODES_LP,
            live_csv_path=QPLIB_LIVE_CSV,
            instance_index=idx,
            ub_info=ub_info,
        )

        if lp["had_unresolved_status"]:
            summary_rows.append({
                "instance_name": name,
                "probtype": data["probtype"],
                "n": data["n"],
                "m_solver": data["m_solver"],
                "ub": shared_ub,
                "ub_source": ub_info.get("source"),
                "lp_nodes": lp["processed_nodes"],
                "lp_final_frontier_lb": lp["final_frontier_lb"],
                "lp_unresolved": True,
                "sdpp_nodes": 0,
                "sdpp_final_frontier_lb": np.nan,
                "sdpp_unresolved": np.nan,
                "complete": True,
                "usable_for_pair": False,
            })

            pd.DataFrame(summary_rows).drop_duplicates(
                subset=["instance_name"], keep="last"
            ).to_csv(QPLIB_BB_SUMMARY_CSV, index=False)

            print("LP unresolved -> SDP' skipped, matching MINLPLib policy.")
            continue

        sdpp = run_tree(
            data=data,
            relaxation="SDP_PRIME",
            shared_upper_bound=shared_ub,
            max_nodes=FIXED_NODES_SDPP,
            live_csv_path=QPLIB_LIVE_CSV,
            instance_index=idx,
            ub_info=ub_info,
        )

        summary_rows.append({
            "instance_name": name,
            "probtype": data["probtype"],
            "n": data["n"],
            "m_solver": data["m_solver"],
            "integrality_relaxed": data["integrality_relaxed"],
            "convex": data["convex"],

            "ub": shared_ub,
            "ub_source": ub_info.get("source"),

            "lp_nodes": lp["processed_nodes"],
            "lp_final_frontier_lb": lp["final_frontier_lb"],
            "lp_unresolved": lp["had_unresolved_status"],

            "sdpp_nodes": sdpp["processed_nodes"],
            "sdpp_final_frontier_lb": sdpp["final_frontier_lb"],
            "sdpp_unresolved": sdpp["had_unresolved_status"],

            "complete": True,
            "usable_for_pair": (
                not lp["had_unresolved_status"]
                and not sdpp["had_unresolved_status"]
                and np.isfinite(lp["final_frontier_lb"])
                and np.isfinite(sdpp["final_frontier_lb"])
            ),
        })

        summary_df = pd.DataFrame(summary_rows).drop_duplicates(
            subset=["instance_name"], keep="last"
        )
        summary_df.to_csv(QPLIB_BB_SUMMARY_CSV, index=False)

        print(
            "LP final LB =", lp["final_frontier_lb"],
            "| SDP' final LB =", sdpp["final_frontier_lb"],
            "| usable =", not sdpp["had_unresolved_status"],
        )

        gc.collect()

    summary_df = pd.DataFrame(summary_rows).drop_duplicates(
        subset=["instance_name"], keep="last"
    ).reset_index(drop=True)

    if QPLIB_LIVE_CSV.exists():
        try:
            pd.read_csv(QPLIB_LIVE_CSV).to_parquet(
                QPLIB_LIVE_PARQUET,
                index=False,
            )
            print("Saved:", QPLIB_LIVE_PARQUET)
        except Exception as e:
            print("[WARN] parquet conversion failed:", repr(e))

    print("\nQPLIB B&B instance summary")
    if not summary_df.empty:
        print("Completed:", len(summary_df))
        print(
            "Usable LP-SDP' pair:",
            int(summary_df["usable_for_pair"].fillna(False).sum()),
        )

    print("Summary:", QPLIB_BB_SUMMARY_CSV)
    print("LIVE   :", QPLIB_LIVE_CSV)

    return summary_df


# RUN THIS CELL TO GENERATE / RESUME THE FIXED-BUDGET QPLIB B&B DATASET.
qplib_bb_summary = run_qplib_bb(
    pkl_files=pkl_files,
    feasible_points=qplib_feasible_points,
)

display(qplib_bb_summary.head())

[1/143] QPLIB_0018 | n=50 m=2
Incumbent UB=-6.38601886211 | source=ipopt:clipped_zero
LP final LB = -137.86797112222234 | SDP' final LB = -89.93953439946289 | usable = True

[2/143] QPLIB_0031 | n=60 m=33
Incumbent UB=15.2005247256 | source=ipopt:clipped_zero
LP final LB = 0.0 | SDP' final LB = -25794.93718091263 | usable = True

[3/143] QPLIB_0032 | n=100 m=53
Incumbent UB=9.94558798396 | source=ipopt:clipped_zero
LP final LB = 0.0 | SDP' final LB = -15552.090905318984 | usable = True

[4/143] QPLIB_0067 | n=80 m=1
Incumbent UB=-112205.360582 | source=ipopt:clipped_zero
LP final LB = -112216.38515901056 | SDP' final LB = -116136.41370447619 | usable = True

[5/143] QPLIB_0343 | n=50 m=2
Incumbent UB=-6.38601886211 | source=ipopt:clipped_zero
LP final LB = -137.86793001111124 | SDP' final LB = -89.93954051761112 | usable = True

[6/143] QPLIB_0633 | n=75 m=2
Incumbent UB=79.5791682108 | source=ipopt:random_0
LP final LB = 2.952142351425 | SDP' final LB = 73.06740407740216 | usable = True

[7/143] QPLIB_0681 | n=215 m=538
Incumbent UB=-48.2634293398 | source=ipopt:random_0
LP final LB = -48.39060000000001 | SDP' final LB = -48.39059998263383 | usable = True

[8/143] QPLIB_0682 | n=261 m=716
Incumbent UB=-48.0430440226 | source=ipopt:random_2
LP final LB = -48.39060000000001 | SDP' final LB = -48.39059998085574 | usable = True

[9/143] QPLIB_0698 | n=118 m=157
Incumbent UB=968572.142565 | source=ipopt:random_3
LP final LB = 603634.4605764172 | SDP' final LB = 343548.2592570262 | usable = True

[10/143] QPLIB_0752 | n=250 m=1
Incumbent UB=-24022.0006762 | source=ipopt:lower_25pct
LP final LB = -39610.5 | SDP' final LB = -25434.666337904906 | usable = True

[11/143] QPLIB_0911 | n=50 m=50
Incumbent UB=-32.1475593361 | source=ipopt:lower_25pct
LP final LB = -71.5698 | SDP' final LB = -35.29890688752888 | usable = True

[12/143] QPLIB_0975 | n=50 m=10
Incumbent UB=-37.6352420415 | source=ipopt:random_4
LP final LB = -70.3357 | SDP' final LB = -40.83570478500514 | usable = True

[13/143] QPLIB_10010 | n=269 m=148
Incumbent UB=-23301.3427401 | source=ipopt:midpoint
LP final LB = -24894.172058823533 | SDP' final LB = -23301.342642055846 | usable = True

[14/143] QPLIB_10040 | n=125 m=6
Incumbent UB=5.48834925712e-10 | source=ipopt:random_0
LP final LB = -21.542857307667227 | SDP' final LB = 1.5692625316217955e-06 | usable = True

[15/143] QPLIB_10041 | n=125 m=6
Incumbent UB=-3.51307934441e-10 | source=ipopt:random_4
LP final LB = -38.48329760710474 | SDP' final LB = 2.8012139655780866e-07 | usable = True

[16/143] QPLIB_10042 | n=125 m=5
Incumbent UB=-22.1649869331 | source=ipopt:random_0
LP final LB = -120.1744827839272 | SDP' final LB = -22.164985436184317 | usable = True

[17/143] QPLIB_10043 | n=150 m=10
Incumbent UB=6.46091397429e-08 | source=ipopt:random_0
LP final LB = -109.42050125010951 | SDP' final LB = 1.4130547724212984e-06 | usable = True

[18/143] QPLIB_10044 | n=150 m=6
Incumbent UB=-10.6367398238 | source=ipopt:random_2
LP final LB = -91.83608350660914 | SDP' final LB = -10.636738564053644 | usable = True

[19/143] QPLIB_10045 | n=150 m=10
Incumbent UB=3.15562684901e-10 | source=ipopt:random_4
LP final LB = -156.60624834729475 | SDP' final LB = 1.887811571798517e-07 | usable = True

[20/143] QPLIB_10046 | n=150 m=6
Incumbent UB=-3.34049185199 | source=ipopt:random_0
LP final LB = -171.98003974641523 | SDP' final LB = -3.34049001030319 | usable = True

[21/143] QPLIB_10047 | n=150 m=10
Incumbent UB=-4.0148141986e-10 | source=ipopt:random_3
LP final LB = -50.772674026917954 | SDP' final LB = 4.2332326772752046e-07 | usable = True

[22/143] QPLIB_10048 | n=150 m=5
Incumbent UB=-17.5464868471 | source=ipopt:midpoint
LP final LB = -173.04195946487354 | SDP' final LB = -17.5464840418999 | usable = True

[23/143] QPLIB_10049 | n=150 m=10
Incumbent UB=-3.13539323999e-10 | source=ipopt:random_2
LP final LB = -127.30624867162953 | SDP' final LB = 2.0622639305445252e-07 | usable = True

[24/143] QPLIB_10050 | n=150 m=5
Incumbent UB=-27.3823323217 | source=ipopt:lower_25pct
LP final LB = -187.5460678514274 | SDP' final LB = -27.382330580763252 | usable = True

[25/143] QPLIB_10051 | n=150 m=10
Incumbent UB=-1.91509093756e-10 | source=ipopt:random_0
LP final LB = -190.83453027135278 | SDP' final LB = 1.81811722777675e-08 | usable = True

[26/143] QPLIB_10052 | n=150 m=6
Incumbent UB=-14.5086183105 | source=ipopt:random_4
LP final LB = -154.21767482913486 | SDP' final LB = -14.508616466265602 | usable = True

[27/143] QPLIB_10053 | n=150 m=10
Incumbent UB=2.0292665194e-09 | source=ipopt:random_1
LP final LB = -317.4339543527431 | SDP' final LB = 4.965033786765138e-06 | usable = True

[28/143] QPLIB_10054 | n=175 m=11
Incumbent UB=-15.208407564 | source=ipopt:random_4
LP final LB = -77.8454032992168 | SDP' final LB = -15.208406386041121 | usable = True

[29/143] QPLIB_10055 | n=175 m=5
Incumbent UB=-5.0326666674 | source=ipopt:lower_25pct
LP final LB = -228.02762270792186 | SDP' final LB = -5.032663386355071 | usable = True

[30/143] QPLIB_10056 | n=175 m=5
Incumbent UB=-35.3245300134 | source=ipopt:clipped_zero
LP final LB = -264.2518606234977 | SDP' final LB = -35.324528523799344 | usable = True

[31/143] QPLIB_10057 | n=200 m=11
Incumbent UB=1.59794702663e-06 | source=ipopt:lower_25pct
LP final LB = -186.7665850401 | SDP' final LB = 1.7429172535851065e-06 | usable = True

[32/143] QPLIB_10058 | n=200 m=11
Incumbent UB=-8.21094177796 | source=ipopt:midpoint
LP final LB = -185.33349960322687 | SDP' final LB = -8.210937881078989 | usable = True

[33/143] QPLIB_10059 | n=200 m=10
Incumbent UB=-3.25654076574e-09 | source=ipopt:random_0
LP final LB = -92.59114923276262 | SDP' final LB = 3.1070171662081197e-07 | usable = True

[34/143] QPLIB_10060 | n=200 m=10
Incumbent UB=8.33261725744e-07 | source=ipopt:random_4
LP final LB = -240.61213375812756 | SDP' final LB = 4.463828085015101e-06 | usable = True

[35/143] QPLIB_10061 | n=200 m=5
Incumbent UB=-25.6795705544 | source=ipopt:random_4
LP final LB = -348.58801446089944 | SDP' final LB = -25.679569172063104 | usable = True

[36/143] QPLIB_10062 | n=200 m=10
Incumbent UB=9.54437370452e-10 | source=ipopt:clipped_zero
LP final LB = -218.87965113851286 | SDP' final LB = 1.940452541764249e-07 | usable = True

[37/143] QPLIB_10063 | n=200 m=5
Incumbent UB=-42.7772234623 | source=ipopt:upper_75pct
LP final LB = -91.20275144712335 | SDP' final LB = -42.777221471165845 | usable = True

[38/143] QPLIB_10064 | n=200 m=11
Incumbent UB=1.03909647191e-09 | source=ipopt:lower_25pct
LP final LB = -99.9056585866298 | SDP' final LB = 4.871996840563695e-08 | usable = True

[39/143] QPLIB_10065 | n=200 m=11
Incumbent UB=-31.1738247127 | source=ipopt:random_0
LP final LB = -253.0687453295221 | SDP' final LB = -31.17382328990872 | usable = True

[40/143] QPLIB_10066 | n=200 m=11
Incumbent UB=-34.093068384 | source=ipopt:clipped_zero
LP final LB = -259.27208986347364 | SDP' final LB = -34.09306491520965 | usable = True

[41/143] QPLIB_10067 | n=200 m=5
Incumbent UB=-34.2857747465 | source=ipopt:random_2
LP final LB = -357.57641649545667 | SDP' final LB = -34.28577155296642 | usable = True

[42/143] QPLIB_10068 | n=200 m=11
Incumbent UB=-33.531458999 | source=ipopt:random_1
LP final LB = -362.23924356142305 | SDP' final LB = -33.53145499107431 | usable = True

[43/143] QPLIB_10069 | n=200 m=10
Incumbent UB=1.0291185995e-09 | source=ipopt:midpoint
LP final LB = -295.15964890116925 | SDP' final LB = 2.5203960312647238e-06 | usable = True

[44/143] QPLIB_10070 | n=200 m=11
Incumbent UB=-28.3022424874 | source=ipopt:random_1
LP final LB = -496.4849713659978 | SDP' final LB = -28.3022410865619 | usable = True

[45/143] QPLIB_10071 | n=200 m=11
Incumbent UB=5.3936471723e-06 | source=ipopt:upper_75pct
LP final LB = -368.03956012922487 | SDP' final LB = 1.9809919205419568e-06 | usable = True

[46/143] QPLIB_10072 | n=75 m=10
Incumbent UB=9.7422287918e-10 | source=ipopt:random_1
LP final LB = -9.39265549937237 | SDP' final LB = 8.899609025623928e-08 | usable = True

[47/143] QPLIB_10073 | n=75 m=6
Incumbent UB=-5.32267704334e-10 | source=ipopt:random_2
LP final LB = -16.252738513777945 | SDP' final LB = 2.0309396950334532e-08 | usable = True

[48/143] QPLIB_10074 | n=75 m=10
Incumbent UB=3.07436234921e-10 | source=ipopt:lower_25pct
LP final LB = -32.05030052667294 | SDP' final LB = 1.5257907508389908e-07 | usable = True

[49/143] QPLIB_1055 | n=40 m=20
Incumbent UB=-33.0370241777 | source=ipopt:random_0
LP final LB = -85.31416250000005 | SDP' final LB = -35.73867455754981 | usable = True

[50/143] QPLIB_1143 | n=40 m=28
Incumbent UB=-56.2364644907 | source=ipopt:midpoint
LP final LB = -128.42496083872018 | SDP' final LB = -66.60030561726485 | usable = True

[51/143] QPLIB_1157 | n=40 m=17
Incumbent UB=-10.9482041436 | source=ipopt:lower_25pct
LP final LB = -14.495173350552696 | SDP' final LB = -12.046755675424572 | usable = True

[52/143] QPLIB_1353 | n=50 m=11
Incumbent UB=-7.71416260086 | source=ipopt:upper_75pct
LP final LB = -15.824188170755203 | SDP' final LB = -8.723632299747543 | usable = True

[53/143] QPLIB_1423 | n=40 m=28
Incumbent UB=-14.9674680739 | source=ipopt:random_4
LP final LB = -24.429178160977546 | SDP' final LB = -15.689611327967787 | usable = True

[54/143] QPLIB_1437 | n=50 m=21
Incumbent UB=-7.78917325867 | source=ipopt:random_4
LP final LB = -14.791807489233975 | SDP' final LB = -9.796344883056754 | usable = True

[55/143] QPLIB_1451 | n=60 m=72
Incumbent UB=-87.5764891571 | source=ipopt:random_1
LP final LB = -179.08005781991906 | SDP' final LB = -105.64472578152916 | usable = True

[56/143] QPLIB_1493 | n=40 m=9
Incumbent UB=-42.4075171991 | source=ipopt:random_0
LP final LB = -80.11894513495959 | SDP' final LB = -51.48543752329634 | usable = True

[57/143] QPLIB_1507 | n=30 m=36
Incumbent UB=-8.30137713949 | source=ipopt:random_4
LP final LB = -16.303727856982448 | SDP' final LB = -8.960859013648683 | usable = True

[58/143] QPLIB_1535 | n=60 m=72
Incumbent UB=-11.549995495 | source=ipopt:random_4
LP final LB = -25.540822438117615 | SDP' final LB = -13.681378198676148 | usable = True

[59/143] QPLIB_1619 | n=50 m=35
Incumbent UB=-9.2173027627 | source=ipopt:midpoint
LP final LB = -21.908720115753432 | SDP' final LB = -10.152002394283791 | usable = True

[60/143] QPLIB_1661 | n=60 m=25
Incumbent UB=-15.9548982724 | source=ipopt:clipped_zero
LP final LB = -28.01726932067428 | SDP' final LB = -18.247669348579056 | usable = True

[61/143] QPLIB_1675 | n=60 m=25
Incumbent UB=-75.6686849855 | source=ipopt:random_3
LP final LB = -141.42734111189827 | SDP' final LB = -90.62059318900509 | usable = True

[62/143] QPLIB_1703 | n=60 m=42
Incumbent UB=-132.380568795 | source=ipopt:midpoint
LP final LB = -294.5258241786112 | SDP' final LB = -150.0409519716946 | usable = True

[63/143] QPLIB_1745 | n=50 m=60
Incumbent UB=-72.3765923259 | source=ipopt:midpoint
LP final LB = -93.21009885106896 | SDP' final LB = -80.70109492391458 | usable = True

[64/143] QPLIB_1773 | n=60 m=13
Incumbent UB=-14.6418617495 | source=ipopt:random_2
LP final LB = -35.17559494660328 | SDP' final LB = -16.974192037046333 | usable = True

[65/143] QPLIB_1886 | n=50 m=50
Incumbent UB=-78.671563732 | source=ipopt:random_1
LP final LB = -142.31887444600756 | SDP' final LB = -85.30256812969928 | usable = True

[66/143] QPLIB_1913 | n=48 m=48
Incumbent UB=-51.8892840942 | source=ipopt:lower_25pct
LP final LB = -69.25749999999996 | SDP' final LB = -56.08886263741057 | usable = True

[67/143] QPLIB_1922 | n=30 m=60
Incumbent UB=-35.7411552329 | source=ipopt:lower_25pct
LP final LB = -49.76479999999998 | SDP' final LB = -38.59785300827681 | usable = True

[68/143] QPLIB_1931 | n=40 m=40
Incumbent UB=-55.7088768267 | source=ipopt:random_3
LP final LB = -86.38249999999998 | SDP' final LB = -59.37936286542779 | usable = True

[69/143] QPLIB_1940 | n=48 m=96
Incumbent UB=-38.3101093594 | source=ipopt:midpoint
LP final LB = -58.16750000000001 | SDP' final LB = -42.476916713250525 | usable = True

[70/143] QPLIB_1967 | n=50 m=75
Incumbent UB=-106.909697958 | source=ipopt:lower_25pct
LP final LB = -278.4306518395516 | SDP' final LB = -118.6119243329821 | usable = True

[71/143] QPLIB_1976 | n=152 m=168
Incumbent UB=-13126.2576748 | source=ipopt:clipped_zero
LP final LB = -43285.55537825024 | SDP' final LB = -48704.241020044974 | usable = True

[72/143] QPLIB_2017 | n=252 m=273
Incumbent UB=-24629.7571232 | source=ipopt:clipped_zero
LP final LB = -75148.97095538706 | SDP' final LB = -79061.45263214747 | usable = True

[73/143] QPLIB_2022 | n=275 m=297
Incumbent UB=-23012.7991879 | source=ipopt:random_1
LP final LB = -50081.106917556775 | SDP' final LB = -51505.8045017614 | usable = True

[74/143] QPLIB_2029 | n=299 m=322
Incumbent UB=-35025.7109905 | source=ipopt:midpoint
LP final LB = -95472.6083688277 | SDP' final LB = -100279.4642854897 | usable = True

[75/143] QPLIB_2047 | n=136 m=2057
Incumbent UB=1120992.06996 | source=ipopt:random_1
LP final LB = 1039119.3405338357 | SDP' final LB = 943748.0182339505 | usable = True

[76/143] QPLIB_2055 | n=153 m=2466
Incumbent UB=3240624.54242 | source=ipopt:random_3
LP final LB = 2375142.9015357196 | SDP' final LB = 2087356.8811576236 | usable = True

[77/143] QPLIB_2060 | n=171 m=2926
Incumbent UB=2488112.19767 | source=ipopt:midpoint
LP final LB = 1738748.9897406544 | SDP' final LB = 1522098.813662743 | usable = True

[78/143] QPLIB_2067 | n=190 m=3440
Incumbent UB=3098850.0096 | source=ipopt:lower_25pct
LP final LB = 1302092.3596394581 | SDP' final LB = 1099080.0871951845 | usable = True

[79/143] QPLIB_2073 | n=210 m=4011
Incumbent UB=9093047.863 | source=ipopt:lower_25pct
LP final LB = 6836399.407275507 | SDP' final LB = 6256888.40966242 | usable = True

[80/143] QPLIB_2077 | n=231 m=4642
Incumbent UB=2838692.72267 | source=ipopt:lower_25pct
LP final LB = 2122813.5983934165 | SDP' final LB = 1933461.1748622963 | usable = True

[81/143] QPLIB_2085 | n=253 m=5336
Incumbent UB=9573255 | source=ipopt:upper_75pct
LP final LB = 5450372.467523794 | SDP' final LB = 4751641.509989943 | usable = True

[82/143] QPLIB_2087 | n=276 m=6096
Incumbent UB=10756299.5 | source=ipopt:midpoint
LP final LB = 1473671.4485631161 | SDP' final LB = 1291424.0619185125 | usable = True

[83/143] QPLIB_2353 | n=240 m=2240
Incumbent UB=-670.781583885 | source=ipopt:random_0
LP final LB = -3464.0 | SDP' final LB = -1966.1915008394294 | usable = True

[84/143] QPLIB_2357 | n=240 m=2240
Incumbent UB=-171.700429388 | source=ipopt:random_1
LP final LB = -1078.5 | SDP' final LB = -730.5961200565048 | usable = True

[85/143] QPLIB_2416 | n=25 m=692
SKIPPED: no verified feasible incumbent.

[86/143] QPLIB_2430 | n=125 m=184
Incumbent UB=-1.97279073696 | source=ipopt:random_3
LP final LB = -10.0 | SDP' final LB = -9.999997895194067 | usable = True

[87/143] QPLIB_2445 | n=143 m=142
Incumbent UB=327.518618602 | source=ipopt:random_3
LP final LB = 85.26035437135172 | SDP' final LB = 10.000000001958842 | usable = True

[88/143] QPLIB_2492 | n=196 m=56
Incumbent UB=2656.55345472 | source=ipopt:clipped_zero
LP final LB = 0.0 | SDP' final LB = -12794.58540738615 | usable = True

[89/143] QPLIB_2512 | n=100 m=40
Incumbent UB=130869.65135 | source=ipopt:random_2
LP final LB = 0.0 | SDP' final LB = -411869.23417995503 | usable = True

[90/143] QPLIB_2590 | n=25 m=500
SKIPPED: no verified feasible incumbent.

[91/143] QPLIB_2658 | n=184 m=345
Incumbent UB=9.24758915548 | source=ipopt:midpoint
LP final LB = 0.0 | SDP' final LB = -1.8759326536610388e-08 | usable = True

[92/143] QPLIB_2698 | n=196 m=93
Incumbent UB=1201.03846915 | source=ipopt:clipped_zero
LP final LB = 648.0 | SDP' final LB = 0.025823804461901682 | usable = True

[93/143] QPLIB_2702 | n=260 m=247
Incumbent UB=1415.24793846 | source=ipopt:clipped_zero
LP final LB = 1415.0 | SDP' final LB = 1415.248048286585 | usable = True

[94/143] QPLIB_2712 | n=200 m=2
Incumbent UB=0.0128668981598 | source=ipopt:midpoint
LP final LB = 0.0 | SDP' final LB = -7.204488516940758 | usable = True

[95/143] QPLIB_2738 | n=199 m=299
Incumbent UB=-4.28419909235 | source=ipopt:midpoint
LP final LB = -5.294909490489324 | SDP' final LB = -5.313391010843053 | usable = True

[96/143] QPLIB_2834 | n=156 m=160
Incumbent UB=365.783604948 | source=ipopt:upper_75pct
LP final LB = 92.55280647738864 | SDP' final LB = 3.253516883419273e-05 | usable = True

[97/143] QPLIB_2894 | n=17 m=213
Incumbent UB=5.99999999909 | source=gurobi_repair
LP final LB = 3.5501134863636366 | SDP' final LB = 3.5501134863635944 | usable = True

[98/143] QPLIB_2987 | n=208 m=396
Incumbent UB=5078.41836348 | source=gurobi_repair
LP final LB = 337.65432098765433 | SDP' final LB = 337.8419580056734 | usable = False

[99/143] QPLIB_2993 | n=266 m=614
Incumbent UB=9350.06715075 | source=gurobi_repair
LP final LB = 66.19834710743802 | SDP' final LB = 66.20212002220809 | usable = False

[100/143] QPLIB_3083 | n=243 m=452
Incumbent UB=5096.61226407 | source=gurobi_repair
LP final LB = 910.8578431372549 | SDP' final LB = 920.586709852266 | usable = False

[101/143] QPLIB_3089 | n=132 m=168
Incumbent UB=312.921538824 | source=ipopt:random_0
LP final LB = 0.0 | SDP' final LB = 2.754924813330976e-07 | usable = True

[102/143] QPLIB_3225 | n=136 m=142
Incumbent UB=511.527241374 | source=ipopt:random_4
LP final LB = 251.20133547522644 | SDP' final LB = 60.00000004118969 | usable = True

[103/143] QPLIB_3307 | n=256 m=64
Incumbent UB=1224.24987064 | source=ipopt:random_1
LP final LB = 0.0 | SDP' final LB = -8510.842486133839 | usable = True

[104/143] QPLIB_3318 | n=25 m=480
SKIPPED: no verified feasible incumbent.

[105/143] QPLIB_3358 | n=158 m=317
Incumbent UB=3.0971140909 | source=ipopt:random_4
LP final LB = 0.0 | SDP' final LB = -9.346479146188358e-11 | usable = True

[106/143] QPLIB_3385 | n=155 m=268
Incumbent UB=12724.6874794 | source=ipopt:clipped_zero
LP final LB = 225.0 | SDP' final LB = 225.20269404254958 | usable = False

[107/143] QPLIB_3387 | n=170 m=141
Incumbent UB=403.195973514 | source=ipopt:random_1
LP final LB = 258.2773377819392 | SDP' final LB = 53.00000000215333 | usable = True

[108/143] QPLIB_3402 | n=144 m=48
Incumbent UB=220075.071621 | source=ipopt:lower_25pct
LP final LB = 0.0 | SDP' final LB = -848689.6548182567 | usable = True

[109/143] QPLIB_3512 | n=191 m=474
Incumbent UB=-48.3906014135 | source=ipopt:upper_75pct
LP final LB = -48.3906 | SDP' final LB = -48.390599920192294 | usable = True

[110/143] QPLIB_3523 | n=182 m=1456
Incumbent UB=-583.501335075 | source=ipopt:random_3
LP final LB = -1105.75 | SDP' final LB = -699.429630776945 | usable = True

[111/143] QPLIB_3562 | n=63 m=42
Incumbent UB=13.65069606 | source=ipopt:random_4
LP final LB = 2.5166666666666666 | SDP' final LB = 0.2705819579493237 | usable = True

[112/143] QPLIB_3587 | n=240 m=76
Incumbent UB=15284.9668949 | source=ipopt:upper_75pct
LP final LB = 0.0 | SDP' final LB = -104845.8262624284 | usable = True

[113/143] QPLIB_3614 | n=210 m=74
Incumbent UB=14229.6267668 | source=ipopt:upper_75pct
LP final LB = 0.0 | SDP' final LB = -80941.90638165212 | usable = True

[114/143] QPLIB_3703 | n=225 m=60
Incumbent UB=383597.485292 | source=ipopt:random_1
LP final LB = 0.0 | SDP' final LB = -1545218.9904130558 | usable = True

[115/143] QPLIB_3714 | n=120 m=80
Incumbent UB=1182.99983413 | source=ipopt:random_4
LP final LB = 0.0 | SDP' final LB = 160.63194659354468 | usable = True

[116/143] QPLIB_3750 | n=210 m=140
Incumbent UB=6347.99911085 | source=ipopt:random_4
LP final LB = 0.0 | SDP' final LB = 538.9125567147739 | usable = True

[117/143] QPLIB_3751 | n=150 m=100
Incumbent UB=2311.99967603 | source=ipopt:random_1
LP final LB = 0.0 | SDP' final LB = 261.85065710022286 | usable = True

[118/143] QPLIB_3762 | n=90 m=480
Incumbent UB=-296.000011057 | source=ipopt:lower_25pct
LP final LB = -554.75 | SDP' final LB = -343.51760364731473 | usable = True

[119/143] QPLIB_3775 | n=180 m=120
Incumbent UB=3989.99943982 | source=ipopt:random_1

,instance_name,probtype,n,m_solver,integrality_relaxed,convex,ub,ub_source,lp_nodes,lp_final_frontier_lb,lp_unresolved,sdpp_nodes,sdpp_final_frontier_lb,sdpp_unresolved,complete,usable_for_pair
0,QPLIB_0018,QCL,50,2,True,None,-6.386019,ipopt:clipped_zero,100,-137.867971,False,100,-89.939534,False,True,True
1,QPLIB_0031,QML,60,33,True,None,15.200525,ipopt:clipped_zero,100,0.000000,False,100,-25794.937181,False,True,True
2,QPLIB_0032,QML,100,53,True,None,9.945588,ipopt:clipped_zero,100,0.000000,False,100,-15552.090905,False,True,True
3,QPLIB_0067,QBL,80,1,True,None,-112205.360582,ipopt:clipped_zero,100,-112216.385159,False,100,-116136.413704,False,True,True
4,QPLIB_0343,QCL,50,2,True,None,-6.386019,ipopt:clipped_zero,100,-137.867930,False,100,-89.939541,False,True,True

In [8]:

# ============================================================
# 5. QPLIB B&B QUICK TARGET SUMMARY
# This is ONLY the initial fixed-100-node tree dataset.
# Final thesis Method 1 / Method 2 time-aware budgets come later.
# ============================================================

def compute_delta(z_lp, z_other):
    if not (np.isfinite(z_lp) and np.isfinite(z_other)):
        return np.nan

    return (
        (float(z_lp) - float(z_other))
        /
        (abs(float(z_lp)) + abs(float(z_other)) + ETA)
    )


if not qplib_bb_summary.empty:
    qplib_bb_summary = qplib_bb_summary.copy()

    qplib_bb_summary["delta_lp_sdpp_fixed100"] = qplib_bb_summary.apply(
        lambda r: compute_delta(
            r["lp_final_frontier_lb"],
            r["sdpp_final_frontier_lb"],
        )
        if bool(r.get("usable_for_pair", False))
        else np.nan,
        axis=1,
    )

    qplib_bb_summary["label_lp_sdpp_fixed100"] = qplib_bb_summary[
        "delta_lp_sdpp_fixed100"
    ].apply(
        lambda d: int(d > -EPS) if np.isfinite(d) else np.nan
    )

    qplib_bb_summary.to_csv(QPLIB_BB_SUMMARY_CSV, index=False)

    print(
        qplib_bb_summary["label_lp_sdpp_fixed100"]
        .value_counts(dropna=False)
        .rename(index={1.0: "LP/near-tie", 0.0: "SDP' clearly stronger"})
    )

    display(
        qplib_bb_summary[
            [
                "instance_name",
                "probtype",
                "n",
                "ub",
                "lp_nodes",
                "sdpp_nodes",
                "lp_final_frontier_lb",
                "sdpp_final_frontier_lb",
                "delta_lp_sdpp_fixed100",
                "label_lp_sdpp_fixed100",
                "usable_for_pair",
            ]
        ].head(20)
    )

label_lp_sdpp_fixed100
SDP' clearly stronger    88
LP/near-tie              48
NaN                       4
Name: count, dtype: int64

,instance_name,probtype,n,ub,lp_nodes,sdpp_nodes,lp_final_frontier_lb,sdpp_final_frontier_lb,delta_lp_sdpp_fixed100,label_lp_sdpp_fixed100,usable_for_pair
0,QPLIB_0018,QCL,50,-6.386019e+00,100,100,-137.867971,-8.993953e+01,-2.103891e-01,0.0,True
1,QPLIB_0031,QML,60,1.520052e+01,100,100,0.000000,-2.579494e+04,1.000000e+00,1.0,True
2,QPLIB_0032,QML,100,9.945588e+00,100,100,0.000000,-1.555209e+04,9.999999e-01,1.0,True
3,QPLIB_0067,QBL,80,-1.122054e+05,100,100,-112216.385159,-1.161364e+05,1.716654e-02,1.0,True
4,QPLIB_0343,QCL,50,-6.386019e+00,100,100,-137.867930,-8.993954e+01,-2.103890e-01,0.0,True
5,QPLIB_0633,QBL,75,7.957917e+01,100,100,2.952142,7.306740e+01,-9.223199e-01,0.0,True
6,QPLIB_0681,LMQ,215,-4.826343e+01,100,100,-48.390600,-4.839060e+01,-1.794357e-10,1.0,True
7,QPLIB_0682,LMQ,261,-4.804304e+01,100,100,-48.390600,-4.839060e+01,-1.978078e-10,1.0,True
8,QPLIB_0698,LMQ,118,9.685721e+05,100,100,603634.460576,3.435483e+05,2.745893e-01,1.0,True
9,QPLIB_0752,QBL,250,-2.402200e+04,100,100,-39610.500000,-2.543467e+04,-2.179383e-01,0.0,True
10,QPLIB_0911,QCQ,50,-3.214756e+01,100,100,-71.569800,-3.529891e+01,-3.393936e-01,0.0,True
11,QPLIB_0975,QCQ,50,-3.763524e+01,100,100,-70.335700,-4.083570e+01,-2.653536e-01,0.0,True
12,QPLIB_10010,LMC,269,-2.330134e+04,100,1,-24894.172059,-2.330134e+04,-3.304933e-02,0.0,True
13,QPLIB_10040,QBL,125,5.488349e-10,100,1,-21.542857,1.569263e-06,-9.999536e-01,0.0,True
14,QPLIB_10041,QBL,125,-3.513079e-10,100,1,-38.483298,2.801214e-07,-9.999740e-01,0.0,True
15,QPLIB_10042,QBL,125,-2.216499e+01,100,1,-120.174483,-2.216499e+01,-6.885568e-01,0.0,True
16,QPLIB_10043,QBL,150,6.460914e-08,100,1,-109.420501,1.413055e-06,-9.999909e-01,0.0,True
17,QPLIB_10044,QBL,150,-1.063674e+01,100,1,-91.836084,-1.063674e+01,-7.923911e-01,0.0,True
18,QPLIB_10045,QBL,150,3.155627e-10,100,1,-156.606248,1.887812e-07,-9.999936e-01,0.0,True
19,QPLIB_10046,QBL,150,-3.340492e+00,100,1,-171.980040,-3.340490e+00,-9.618873e-01,0.0,True